name: Documentovisco API CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions: write-all

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0

  #   - name: Lint codebase
  #     uses: super-linter/super-linter@v5
  #     env:
  #       VALIDATE_ALL_CODEBASE: true
  #       DEFAULT_BRANCH: master
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip --file pom.xml

  test:
    runs-on: ubuntu-latest
    needs: build
    if: always()

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Unit tests
      run: mvn test

    - name: Publish test reports
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          target/surefire-reports/TEST-*.xml

  discord-notify:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    if: ${{ always() }}
    
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'Documentovisco API Job Runner'
          title: '${{ github.workflow }}: {{STATUS}}'
